
import { ModelConfig } from './types';

export const MODELS: ModelConfig[] = [
  // --- 几何类 (20) ---
  { id: 'p1', category: 'primitive', name: '倒角工业方体', type: 'box', color: '#6366f1', metalness: 0.5, roughness: 0.2, description: '标准倒角立方体。' },
  { id: 'p2', category: 'primitive', name: '高精拓扑球体', type: 'sphere', color: '#10b981', metalness: 0.4, roughness: 0.3, description: '多段细分完美球。' },
  { id: 'p3', category: 'primitive', name: '黄金比例环面', type: 'torus', color: '#f59e0b', metalness: 0.8, roughness: 0.1, description: '标准环形结构。' },
  { id: 'p4', category: 'primitive', name: '艺术三叶扭结', type: 'knot', color: '#ec4899', metalness: 0.7, roughness: 0.1, description: '拓扑艺术形态。' },
  { id: 'p5', category: 'primitive', name: '正八面晶体', type: 'octahedron', color: '#8b5cf6', metalness: 0.9, roughness: 0.1, description: '天然矿石质感。' },
  { id: 'p6', category: 'primitive', name: '正四面体棱镜', type: 'tetrahedron', color: '#ef4444', metalness: 0.6, roughness: 0.4, description: '极简尖锐造型。' },
  { id: 'p7', category: 'primitive', name: '正二十面体', type: 'icosahedron', color: '#3b82f6', metalness: 0.3, roughness: 0.7, description: '多面拓扑构造。' },
  { id: 'p8', category: 'primitive', name: '正十二面体', type: 'dodecahedron', color: '#14b8a6', metalness: 0.5, roughness: 0.5, description: '经典数学几何。' },
  { id: 'p9', category: 'primitive', name: '精密工业圆柱', type: 'cylinder', color: '#64748b', metalness: 0.8, roughness: 0.2, description: '轴类零件基础。' },
  { id: 'p10', category: 'primitive', name: '几何尖端圆锥', type: 'cone', color: '#f97316', metalness: 0.4, roughness: 0.6, description: '指向性几何体。' },
  { id: 'p11', category: 'primitive', name: '药用级胶囊体', type: 'capsule', color: '#fbbf24', metalness: 0.2, roughness: 0.1, description: '平滑倒角胶囊。' },
  { id: 'p12', category: 'primitive', name: '轻盈二维圆环', type: 'ring', color: '#a855f7', metalness: 0.9, roughness: 0.1, description: '扁平圆环。' },
  { id: 'p13', category: 'primitive', name: '管状抽象结构', type: 'tube', color: '#0ea5e9', metalness: 0.6, roughness: 0.3, description: '管道流体形态。' },
  { id: 'p14', category: 'primitive', name: '重金属扭结', type: 'torusKnotAlt', color: '#475569', metalness: 1.0, roughness: 0.1, description: '工业硬派扭结。' },
  { id: 'p15', category: 'primitive', name: '悬浮显示面板', type: 'plane', color: '#ffffff', metalness: 0.1, roughness: 0.9, description: '单面显示单元。' },
  { id: 'p16', category: 'primitive', name: '完美扁平圆盘', type: 'circle', color: '#ec4899', metalness: 0.4, roughness: 0.6, description: '2D填充圆面。' },
  { id: 'p17', category: 'primitive', name: '陶瓷艺术花瓶', type: 'lathe', color: '#f1f5f9', metalness: 0.1, roughness: 0.1, description: '旋转成型陶瓷。' },
  { id: 'p18', category: 'primitive', name: '心形拉伸造型', type: 'extrude', color: '#f43f5e', metalness: 0.2, roughness: 0.8, description: '自定义路径拉伸。' },
  { id: 'p19', category: 'primitive', name: '多维棱镜体', type: 'polyhedron', color: '#f97316', metalness: 0.5, roughness: 0.5, description: '不规则多面体。' },
  { id: 'p20', category: 'primitive', name: '双棱锥结晶', type: 'dipyramid', color: '#fb7185', metalness: 0.8, roughness: 0.2, description: '对称结晶体。' },

  // --- 植物类 (20) ---
  { id: 't1', category: 'tree', name: '极细分节翠竹', type: 'bamboo', color: '#16a34a', metalness: 0.1, roughness: 0.5, description: '写实翠竹。' },
  { id: 't2', category: 'tree', name: '金秋银杏', type: 'ginkgo', color: '#eab308', metalness: 0, roughness: 1, description: '扇形金叶。' },
  { id: 't3', category: 'tree', name: '江南垂柳', type: 'willow', color: '#a3e635', metalness: 0, roughness: 0.8, description: '丝缕垂挂。' },
  { id: 't4', category: 'tree', name: '火红枫树', type: 'maple', color: '#dc2626', metalness: 0, roughness: 0.9, description: '五角红叶。' },
  { id: 't5', category: 'tree', name: '猴面包树', type: 'baobab', color: '#78350f', metalness: 0, roughness: 1, description: '巨型躯干。' },
  { id: 't6', category: 'tree', name: '云雾粉樱', type: 'cherry', color: '#fbcfe8', metalness: 0, roughness: 1, description: '浪漫樱花。' },
  { id: 't7', category: 'tree', name: '高山云松', type: 'pine', color: '#064e3b', metalness: 0.1, roughness: 0.9, description: '塔状层叠。' },
  { id: 't8', category: 'tree', name: '海岛写实棕榈', type: 'palm', color: '#22c55e', metalness: 0.1, roughness: 0.5, description: '热带风情。' },
  { id: 't9', category: 'tree', name: '荒漠巨人仙人掌', type: 'cactus', color: '#15803d', metalness: 0.1, roughness: 0.7, description: '荒漠之魂。' },
  { id: 't10', category: 'tree', name: '月季灌木丛', type: 'shrub', color: '#be185d', metalness: 0.1, roughness: 0.8, description: '繁花点缀。' },
  { id: 't11', category: 'tree', name: '千年古橡树', type: 'oak', color: '#166534', metalness: 0, roughness: 1, description: '广阔树冠。' },
  { id: 't12', category: 'tree', name: '墓园柏树', type: 'cypress', color: '#064e3b', metalness: 0, roughness: 0.9, description: '修长幽深。' },
  { id: 't13', category: 'tree', name: '白杨树', type: 'poplar', color: '#86efac', metalness: 0, roughness: 0.7, description: '笔直挺拔。' },
  { id: 't14', category: 'tree', name: '白桦树', type: 'birch', color: '#f8fafc', metalness: 0.1, roughness: 0.8, description: '银色树干。' },
  { id: 't15', category: 'tree', name: '禅意罗汉松盆景', type: 'bonsai', color: '#0f5132', metalness: 0, roughness: 1, description: '曲径通幽。' },
  { id: 't16', category: 'tree', name: '红树林', type: 'mangrove', color: '#065f46', metalness: 0, roughness: 0.9, description: '错综根系。' },
  { id: 't17', category: 'tree', name: '北美巨杉', type: 'redwood', color: '#451a03', metalness: 0, roughness: 1, description: '擎天之柱。' },
  { id: 't18', category: 'tree', name: '红富士苹果树', type: 'apple', color: '#b91c1c', metalness: 0.2, roughness: 0.4, description: '硕果累累。' },
  { id: 't19', category: 'tree', name: '大叶香蕉树', type: 'banana', color: '#4ade80', metalness: 0.1, roughness: 0.6, description: '阔叶植被。' },
  { id: 't20', category: 'tree', name: '史前巨蕨', type: 'fern', color: '#15803d', metalness: 0, roughness: 0.8, description: '原始孢子。' },

  // --- 动物类 (20) ---
  { id: 'a1', category: 'animal', name: '解剖级大熊猫', type: 'panda', color: '#ffffff', metalness: 0, roughness: 1, description: '黑白国宝。' },
  { id: 'a2', category: 'animal', name: '威猛孟加拉虎', type: 'tiger', color: '#f97316', metalness: 0, roughness: 0.8, description: '百兽之王。' },
  { id: 'a3', category: 'animal', name: '帝企鹅绅士', type: 'penguin', color: '#1e293b', metalness: 0.1, roughness: 0.4, description: '极地向导。' },
  { id: 'a4', category: 'animal', name: '深海蓝鲸', type: 'whale', color: '#3b82f6', metalness: 0.2, roughness: 0.3, description: '海洋巨兽。' },
  { id: 'a5', category: 'animal', name: '长耳玉兔', type: 'rabbit', color: '#f1f5f9', metalness: 0, roughness: 1, description: '机敏灵动。' },
  { id: 'a6', category: 'animal', name: '优雅长颈鹿', type: 'giraffe', color: '#eab308', metalness: 0, roughness: 0.7, description: '草原哨兵。' },
  { id: 'a7', category: 'animal', name: '忠诚柴犬', type: 'dog', color: '#d97706', metalness: 0, roughness: 0.9, description: '温暖陪伴。' },
  { id: 'a8', category: 'animal', name: '搏击长空雄鹰', type: 'eagle', color: '#451a03', metalness: 0.1, roughness: 0.6, description: '天空霸主。' },
  { id: 'a9', category: 'animal', name: '潜伏蟒蛇', type: 'snake', color: '#064e3b', metalness: 0.2, roughness: 0.4, description: '隐匿猎手。' },
  { id: 'a10', category: 'animal', name: '捕猎蜘蛛', type: 'spider', color: '#020617', metalness: 0.6, roughness: 0.1, description: '暗影织网。' },
  { id: 'a11', category: 'animal', name: '非洲大象', type: 'elephant', color: '#94a3b8', metalness: 0, roughness: 1, description: '陆地巨人。' },
  { id: 'a12', category: 'animal', name: '草原雄狮', type: 'lion', color: '#f59e0b', metalness: 0.1, roughness: 0.9, description: '荣耀领袖。' },
  { id: 'a13', category: 'animal', name: '大白鲨', type: 'shark', color: '#64748b', metalness: 0.3, roughness: 0.2, description: '深海顶级掠食。' },
  { id: 'a14', category: 'animal', name: '幻彩蝴蝶', type: 'butterfly', color: '#d946ef', metalness: 0.5, roughness: 0.3, description: '梁祝化蝶。' },
  { id: 'a15', category: 'animal', name: '汗血宝马', type: 'horse', color: '#78350f', metalness: 0.2, roughness: 0.5, description: '千里良驹。' },
  { id: 'a16', category: 'animal', name: '赤狐', type: 'fox', color: '#ea580c', metalness: 0, roughness: 0.8, description: '森林智者。' },
  { id: 'a17', category: 'animal', name: '雪鸮', type: 'owl', color: '#f8fafc', metalness: 0, roughness: 1, description: '暗夜守护。' },
  { id: 'a18', category: 'animal', name: '尼罗河鳄鱼', type: 'crocodile', color: '#365314', metalness: 0.1, roughness: 0.8, description: '水中潜龙。' },
  { id: 'a19', category: 'animal', name: '袋鼠妈妈', type: 'kangaroo', color: '#a16207', metalness: 0, roughness: 0.9, description: '育儿能手。' },
  { id: 'a20', category: 'animal', name: '深海梭子蟹', type: 'crab', color: '#ef4444', metalness: 0.4, roughness: 0.2, description: '横行无忌。' },
];
