
import { ModelConfig } from './types';

export const MODELS: ModelConfig[] = [
  // --- 几何类 (20) ---
  { id: 'p1', category: 'primitive', name: '倒角方体', type: 'box', color: '#6366f1', metalness: 0.5, roughness: 0.2, description: '标准倒角立方体。', emoji: '📦' },
  { id: 'p2', category: 'primitive', name: '高精球体', type: 'sphere', color: '#10b981', metalness: 0.4, roughness: 0.3, description: '多段细分完美球。', emoji: '🔮' },
  { id: 'p3', category: 'primitive', name: '比例环面', type: 'torus', color: '#f59e0b', metalness: 0.8, roughness: 0.1, description: '标准环形结构。', emoji: '🍩' },
  { id: 'p4', category: 'primitive', name: '艺术扭结', type: 'knot', color: '#ec4899', metalness: 0.7, roughness: 0.1, description: '拓扑艺术形态。', emoji: '🥨' },
  { id: 'p5', category: 'primitive', name: '正八面体', type: 'octahedron', color: '#8b5cf6', metalness: 0.9, roughness: 0.1, description: '天然矿石质感。', emoji: '💎' },
  { id: 'p6', category: 'primitive', name: '四面棱镜', type: 'tetrahedron', color: '#ef4444', metalness: 0.6, roughness: 0.4, description: '极简尖锐造型。', emoji: '🔺' },
  { id: 'p7', category: 'primitive', name: '二十面体', type: 'icosahedron', color: '#3b82f6', metalness: 0.3, roughness: 0.7, description: '多面拓扑构造。', emoji: '⚽' },
  { id: 'p8', category: 'primitive', name: '十二面体', type: 'dodecahedron', color: '#14b8a6', metalness: 0.5, roughness: 0.5, description: '经典数学几何。', emoji: '🎲' },
  { id: 'p9', category: 'primitive', name: '精密圆柱', type: 'cylinder', color: '#64748b', metalness: 0.8, roughness: 0.2, description: '轴类零件基础。', emoji: '🔋' },
  { id: 'p10', category: 'primitive', name: '尖端圆锥', type: 'cone', color: '#f97316', metalness: 0.4, roughness: 0.6, description: '指向性几何体。', emoji: '🍦' },
  { id: 'p11', category: 'primitive', name: '胶囊体', type: 'capsule', color: '#fbbf24', metalness: 0.2, roughness: 0.1, description: '平滑倒角胶囊。', emoji: '💊' },
  { id: 'p12', category: 'primitive', name: '二维圆环', type: 'ring', color: '#a855f7', metalness: 0.9, roughness: 0.1, description: '扁平圆环。', emoji: '⭕' },
  { id: 'p13', category: 'primitive', name: '抽象管状', type: 'tube', color: '#0ea5e9', metalness: 0.6, roughness: 0.3, description: '管道流体形态。', emoji: '🚇' },
  { id: 'p14', category: 'primitive', name: '金属扭结', type: 'torusKnotAlt', color: '#475569', metalness: 1.0, roughness: 0.1, description: '工业硬派扭结。', emoji: '⛓️' },
  { id: 'p15', category: 'primitive', name: '显示面板', type: 'plane', color: '#ffffff', metalness: 0.1, roughness: 0.9, description: '单面显示单元。', emoji: '🖼️' },
  { id: 'p16', category: 'primitive', name: '扁平圆盘', type: 'circle', color: '#ec4899', metalness: 0.4, roughness: 0.6, description: '2D填充圆面。', emoji: '📀' },
  { id: 'p17', category: 'primitive', name: '陶瓷花瓶', type: 'lathe', color: '#f1f5f9', metalness: 0.1, roughness: 0.1, description: '旋转成型陶瓷。', emoji: '🏺' },
  { id: 'p18', category: 'primitive', name: '心形拉伸', type: 'extrude', color: '#f43f5e', metalness: 0.2, roughness: 0.8, description: '自定义路径拉伸。', emoji: '❤️' },
  { id: 'p19', category: 'primitive', name: '多维棱镜', type: 'polyhedron', color: '#f97316', metalness: 0.5, roughness: 0.5, description: '不规则多面体。', emoji: '🧩' },
  { id: 'p20', category: 'primitive', name: '结晶双锥', type: 'dipyramid', color: '#fb7185', metalness: 0.8, roughness: 0.2, description: '对称结晶体。', emoji: '⚔️' },

  // --- 植物类 (20) ---
  { id: 't1', category: 'tree', name: '翠竹', type: 'bamboo', color: '#16a34a', metalness: 0.1, roughness: 0.5, description: '写实翠竹。', emoji: '🎋' },
  { id: 't2', category: 'tree', name: '银杏', type: 'ginkgo', color: '#eab308', metalness: 0, roughness: 1, description: '扇形金叶。', emoji: '🍂' },
  { id: 't3', category: 'tree', name: '垂柳', type: 'willow', color: '#a3e635', metalness: 0, roughness: 0.8, description: '丝缕垂挂。', emoji: '🌿' },
  { id: 't4', category: 'tree', name: '枫树', type: 'maple', color: '#dc2626', metalness: 0, roughness: 0.9, description: '五角红叶。', emoji: '🍁' },
  { id: 't5', category: 'tree', name: '猴面包', type: 'baobab', color: '#78350f', metalness: 0, roughness: 1, description: '巨型躯干。', emoji: '🪵' },
  { id: 't6', category: 'tree', name: '樱花', type: 'cherry', color: '#fbcfe8', metalness: 0, roughness: 1, description: '浪漫樱花。', emoji: '🌸' },
  { id: 't7', category: 'tree', name: '云松', type: 'pine', color: '#064e3b', metalness: 0.1, roughness: 0.9, description: '塔状层叠。', emoji: '🌲' },
  { id: 't8', category: 'tree', name: '棕榈', type: 'palm', color: '#22c55e', metalness: 0.1, roughness: 0.5, description: '热带风情。', emoji: '🌴' },
  { id: 't9', category: 'tree', name: '仙人掌', type: 'cactus', color: '#15803d', metalness: 0.1, roughness: 0.7, description: '荒漠之魂。', emoji: '🌵' },
  { id: 't10', category: 'tree', name: '月季', type: 'shrub', color: '#be185d', metalness: 0.1, roughness: 0.8, description: '繁花点缀。', emoji: '🌺' },
  { id: 't11', category: 'tree', name: '橡树', type: 'oak', color: '#166534', metalness: 0, roughness: 1, description: '广阔树冠。', emoji: '🌳' },
  { id: 't12', category: 'tree', name: '柏树', type: 'cypress', color: '#064e3b', metalness: 0, roughness: 0.9, description: '修长幽深。', emoji: '🌲' },
  { id: 't13', category: 'tree', name: '白杨', type: 'poplar', color: '#86efac', metalness: 0, roughness: 0.7, description: '笔直挺拔。', emoji: '🍃' },
  { id: 't14', category: 'tree', name: '白桦', type: 'birch', color: '#f8fafc', metalness: 0.1, roughness: 0.8, description: '银色树干。', emoji: '🎋' },
  { id: 't15', category: 'tree', name: '盆景', type: 'bonsai', color: '#0f5132', metalness: 0, roughness: 1, description: '曲径通幽。', emoji: '🎍' },
  { id: 't16', category: 'tree', name: '红树', type: 'mangrove', color: '#065f46', metalness: 0, roughness: 0.9, description: '错综根系。', emoji: '🌱' },
  { id: 't17', category: 'tree', name: '红杉', type: 'redwood', color: '#451a03', metalness: 0, roughness: 1, description: '擎天之柱。', emoji: '🪵' },
  { id: 't18', category: 'tree', name: '苹果树', type: 'apple', color: '#b91c1c', metalness: 0.2, roughness: 0.4, description: '硕果累累。', emoji: '🍎' },
  { id: 't19', category: 'tree', name: '香蕉树', type: 'banana', color: '#4ade80', metalness: 0.1, roughness: 0.6, description: '阔叶植被。', emoji: '🍌' },
  { id: 't20', category: 'tree', name: '巨蕨', type: 'fern', color: '#15803d', metalness: 0, roughness: 0.8, description: '原始孢子。', emoji: '🌿' },

  // --- 动物类 (20) ---
  { id: 'a1', category: 'animal', name: '大熊猫', type: 'panda', color: '#ffffff', metalness: 0, roughness: 1, description: '黑白国宝。', emoji: '🐼' },
  { id: 'a2', category: 'animal', name: '老虎', type: 'tiger', color: '#f97316', metalness: 0, roughness: 0.8, description: '百兽之王。', emoji: '🐯' },
  { id: 'a3', category: 'animal', name: '企鹅', type: 'penguin', color: '#1e293b', metalness: 0.1, roughness: 0.4, description: '极地向导。', emoji: '🐧' },
  { id: 'a4', category: 'animal', name: '蓝鲸', type: 'whale', color: '#3b82f6', metalness: 0.2, roughness: 0.3, description: '海洋巨兽。', emoji: '🐋' },
  { id: 'a5', category: 'animal', name: '兔子', type: 'rabbit', color: '#f1f5f9', metalness: 0, roughness: 1, description: '机敏灵动。', emoji: '🐰' },
  { id: 'a6', category: 'animal', name: '长颈鹿', type: 'giraffe', color: '#eab308', metalness: 0, roughness: 0.7, description: '草原哨兵。', emoji: '🦒' },
  { id: 'a7', category: 'animal', name: '柴犬', type: 'dog', color: '#d97706', metalness: 0, roughness: 0.9, description: '温暖陪伴。', emoji: '🐕' },
  { id: 'a8', category: 'animal', name: '雄鹰', type: 'eagle', color: '#451a03', metalness: 0.1, roughness: 0.6, description: '天空霸主。', emoji: '🦅' },
  { id: 'a9', category: 'animal', name: '蟒蛇', type: 'snake', color: '#064e3b', metalness: 0.2, roughness: 0.4, description: '隐匿猎手。', emoji: '🐍' },
  { id: 'a10', category: 'animal', name: '蜘蛛', type: 'spider', color: '#020617', metalness: 0.6, roughness: 0.1, description: '暗影织网。', emoji: '🕷️' },
  { id: 'a11', category: 'animal', name: '大象', type: 'elephant', color: '#94a3b8', metalness: 0, roughness: 1, description: '陆地巨人。', emoji: '🐘' },
  { id: 'a12', category: 'animal', name: '狮子', type: 'lion', color: '#f59e0b', metalness: 0.1, roughness: 0.9, description: '荣耀领袖。', emoji: '🦁' },
  { id: 'a13', category: 'animal', name: '鲨鱼', type: 'shark', color: '#64748b', metalness: 0.3, roughness: 0.2, description: '深海顶级掠食。', emoji: '🦈' },
  { id: 'a14', category: 'animal', name: '蝴蝶', type: 'butterfly', color: '#d946ef', metalness: 0.5, roughness: 0.3, description: '梁祝化蝶。', emoji: '🦋' },
  { id: 'a15', category: 'animal', name: '宝马', type: 'horse', color: '#78350f', metalness: 0.2, roughness: 0.5, description: '千里良驹。', emoji: '🐎' },
  { id: 'a16', category: 'animal', name: '赤狐', type: 'fox', color: '#ea580c', metalness: 0, roughness: 0.8, description: '森林智者。', emoji: '🦊' },
  { id: 'a17', category: 'animal', name: '雪鸮', type: 'owl', color: '#f8fafc', metalness: 0, roughness: 1, description: '暗夜守护。', emoji: '🦉' },
  { id: 'a18', category: 'animal', name: '鳄鱼', type: 'crocodile', color: '#365314', metalness: 0.1, roughness: 0.8, description: '水中潜龙。', emoji: '🐊' },
  { id: 'a19', category: 'animal', name: '袋鼠', type: 'kangaroo', color: '#a16207', metalness: 0, roughness: 0.9, description: '育儿能手。', emoji: '🦘' },
  { id: 'a20', category: 'animal', name: '螃蟹', type: 'crab', color: '#ef4444', metalness: 0.4, roughness: 0.2, description: '横行无忌。', emoji: '🦀' },
];
